version: '3.8'

services:
  rcsvision:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_DOCUWARE_WORKFLOW_API_KEY=${VITE_DOCUWARE_WORKFLOW_API_KEY}
        - VITE_DOCUWARE_WORKFLOW_URL=${VITE_DOCUWARE_WORKFLOW_URL}
        - VITE_DOCUWARE_ADMIN_API_KEY=${VITE_DOCUWARE_ADMIN_API_KEY}
        - VITE_DOCUWARE_ADMIN_URL=${VITE_DOCUWARE_ADMIN_URL}
    container_name: vision
    ports:
      - "3013:3001" # Map fixed host port 3013 to 3001 in the container
    restart: always
    environment:
      - NODE_ENV=production
